### PR TITLE
Spritz repeated function calls with praise

### PR DESCRIPTION
**Pull request by collinschwantes**
Creates a function called `spritz` that counts the number of times you've run a particular function

### CODE REVIEW

**Comment by EllaKaye** [comment]
Hey @collinschwantes Thanks for the contribution 😄 It's a fun idea! It took me a while to see how it was working (and for a while I thought it wasn't) so, may I make a suggestion, please? Can you print out the (tipsy/drunk) praise *after* `func` has been evaluated? Otherwise, at least with the default `func` of `devtools::check()`, the praise gets printed straight after the call, but the output from `check` comes so thick and fast that said praise disappears from the console before there's been a chance to notice it there.

A few other notes:
- `devtools::check()` now produces a note for {aperol}: `spritz: no visible binding for '<<-' assignment to ‘spritz_count’` -- are you be able to eliminate that note?
- The documentation for `spritz()` has a (not-run) example with the argument `times = 3`, but I think that needs updating to `runs = 3` (or perhaps even better, to `runs = 4` to show changing the default)
- Please add yourself as an author in `DESCRIPTION` - contributing a whole function certainly warrants that.
- Please bump the version by running `usethis::use_version("minor")`
- Please add `NEWS.md` to list your contribution for the new version (`usethis::use_news_md()`)

If that's too much of a to-do list, please do as much of that as you're willing and I'll pick up the rest. 

Thanks again for your interest in {aperol} and you contribution to it 😄

**Comment by EllaKaye** [comment]
Ooh, I just had another thought. We could really lean into the idea of the praise getting drunker the more times you call the function by making use of the `repeat_words` and `repeat_times` arguments to `drunk` when called from within `spritz`, e.g. in `spritz.R`, lines 60-62 could be

```
   if(diff_runs >= 3){
     print(drunk(repeat_words = diff_runs - 2, repeat_times = 2:(diff_runs - 1), template = template))
   }
``` 
So, when `diff_runs = 3`, one word will appear twice. When `diff_runs = 4`, two words are repeated, one of them appears twice, one appears three times. When `diff_runs = 5`, three words are repeated, one of them appears twice, one appears three times, one appears four times, etc.

What do you think?

**Comment by EllaKaye** [comment]
Oh, hang on, my above suggestion leads to a bug when `diff_runs - 2` is greater than the number of words in the template. This fixes that:

```
# drunk praise
praise_length <- length(strsplit(template, " ")[[1]])
rep_n <- min(diff_runs - 2, praise_length)

 if (diff_runs >= 3) {
     print(drunk(repeat_words = rep_n, repeat_times = 2:(rep_n + 1), template = template))
   }
```

**Comment by collinschwantes** [comment]
@EllaKaye I can't seem to get the note to go away. I was surprised it showed up given that `<<-` is part of base R.

**Comment by EllaKaye** [comment]
Thanks @collinschwantes 😄 

I've been reading more about it, and I think the way to get rid of the NOTE, and package best-practice anyway, is to avoid the use of global variables and use internal data/environments instead, as per [this section of the R packages book](https://r-pkgs.org/data.html#sec-data-state) (see also this [SO question](https://stackoverflow.com/questions/28312408/no-visible-binding-for-assignment)). Would you be willing to refactor the code in that way? I've never used this technique, but I'm also happy to give it a go (at some point). (As a side note, it feels completely joyous that a package that started as a joke is turning out to be a great learning experience for me as more people get involved with it).

In the meantime, I'd be happy to merge this as version 0.2.0 and leave the refactor for 0.3.0, except that there's one thing now that seems strange to me. When I was testing the previous version of this PR, I ran `spritz(func = "1+1")`, since that runs faster than using the default `devtools::check()` and, sure enough, I would get `2` in the console. For some reason that is not currently clear to me, that is no longer happening. Running with the default `func` or, say `func = devtools::document()` does indeed `eval(parse())` those functions, but something like `spritz(func = "1+1")` or `spritz(func = "sum(1:2)")` doesn't (even though `eval(parse(text = "1+1"))` does return `2`. There's nothing obvious I can see in the updated code to explain this. Is the same happening for you? Can you see what I'm missing?

**Comment by collinschwantes** [comment]
its likely because the function evaluation  is no longer that the last item to be run in the function - let me check it out

**Comment by collinschwantes** [comment]
Seems much cleaner/safer to use an environment in the package - went with `the` as in the book. I also added an example with a custom function called `sleep_add` so you can see the print out ahead of the function. 

`devtools::check()` and `devtools::document()` seem to reset `the$spritz_count` variable when testing in aperol. Other calls like `package::function()` work e.g. `usethis::user_r("delete_me")`

**Comment by collinschwantes** [comment]
@EllaKaye I think this is ready to go 🍹

**Comment by EllaKaye** [comment]
Thanks @collinschwantes. I'm much preferring this local environment approach to adding something to the global environment 😄 

Now, though, I'm having the opposite thing happen to previously. With a certain supplied `func`s, e.g. `spritz(func = "1+1")`, `spritz` works as expected, but now when I run the default `spritz()`, `devtools::check()` does run, but now I'm not seeing any (garbled) praise output, no matter how many times in quick succession I run it.

When I try `spritz(func = "devtools::document()")`, after the function runs, I get a `NULL` printed out in the console - this happens for all runs (even the first) and, again, I never see praise. (I don't see a `NULL` for just `spritz()` though). 🤔 

Is that happening for you? At first glance, I can't see why this might be. Do you have any ideas?

**Comment by collinschwantes** [comment]
I think the environment is reset when running {devtools} within the package project. Curious if the same thing would happen if installed and run while developing a different project.

**Comment by EllaKaye** [comment]
Hi @collinschwantes. Sorry it's taken a little while to get back to you on this. Your hunch was right about the environment. `spritz()` works fine with devtools functions when developing any package other than aperol itself.

I've committed a few tweaks to the function. I added some checks on the arguments (I got caught out by a cryptic error message when I accidentally forgot to turn `func` into a string). I also switched round the order of things, so that `func` evaluates before the praise is printed. I think this has two advantages - having the praise print last means it doesn't get lost when `func` prints a lot of output in the console (as it does with the default `devtools::check()`). Also, by just evaluating the function, rather than returning it, we don't get a `NULL` printed when the function passed to `func` returns `NULL` (as is the case with, say `devtools::document()`, which returns `NULL` via a call to `invisible()`). 

Also, I've been meaning for a while to learn how to use the [styler](https://styler.r-lib.org) package, and this gave me a great opportunity to do that, so I've committed the changes from running `styler::style_pkg()` (this prompted changes in other files as well). I also updated `NEWS.md` to credit you and link to this PR.

Are you happy with these changes? Could you pull them into your local copy and give it a final spin your end to check everything is still working as you envisaged. If so, I'm happy to merge and release v0.2.0 😄 

I forgot to say in my previous comment that I like your change to making the praise a message rather than plain printing it - it stands out better that way.

I know this PR is probably taking longer than you anticipated to get merged, but I hope you've enjoyed working on it as much as I have. I've learnt a lot from it, especially having the opportunity to learn about using environments in this way.

**Comment by collinschwantes** [comment]
@EllaKaye Hey - happy with the changes - its definitely been fun working on this and I've also learned a lot. Its fun to have a sandbox package to play around with - maybe the next PR will be using `renv` in a package development setting.

**Comment by EllaKaye** [comment]
Brilliant. Thanks @collinschwantes. I'll merge that now 😄 

I made one final tweak - I changed the order of the arguments to put `func` first, as I thought that was the argument another user would be most likely to want to change. I've also added a note about `spritz()` to the README. 

Thanks again for this!

**Pull request merged**
